convert website source to Markdown, print message from installer about Cygwin paths
tlaplus/tlapm pull request #43
Opened 2021-07-01 12:31 UTC by johnyf

These changes include:

- convert the TLAPS website sources from HTML to Markdown. The conversion from Markdown to HTML is now done using [`pandoc`](https://pandoc.org). A little HTML remains here and there inside the Markdown, to preserve some of the original formatting. The resulting website looks almost the same with before.

- move tutorial material from under the directory `doc/web/` to the directory `doc/doc/`.

- add a `Makefile` for the website, to:
  - copy specific files from under `doc/doc/` to under `doc/web/content/`
  - call a Python script that prepends HTML headers and appends HTML footers to Markdown sources, and then converts them to HTML files by calling `pandoc`

- add a message to the installer that informs about `PATH` updates that may be needed on Windows in order to call a `tlapm` that has been installed within Cygwin, from a Windows command-line environment

- use lowercase paths for website files, update the website links accordingly, and also the JavaScript script for generating HTML headers (specifically the webpage menus)

Please find more details about these changes in the commit messages.

2022-04-01 20:03 UTC, damiendoligez requested changes
I have built the new website on our Web server. I had to make two changes (see below) to get it to compile. The result is available here: http://tla.msr-inria.inria.fr/tlaps-new

If you have a look, you'll see that most links are broken because they are still in upper case, while you changed the file names to lower case.

2022-05-12 01:15 UTC, johnyf commented
Thank you for reviewing the changes and building the website, I have updated the changes to correct the errors.

In the renaming of filepaths to lowercase, there were links in HTML that I had not renamed, and those caused the linking errors in the built website.

2022-06-27 14:52 UTC, damiendoligez requested changes
There are still broken links, especially in the menus at the top and left of the page. Since they are generated from `MENUMAP` in `header.py`, I guess you'll have to add a function to lowercase the menu items.

2022-06-27 14:52 UTC, damiendoligez commented on doc/web/assets/header.py
> +        href="{{base}}Home.html">
```suggestion
        href="{{base}}home.html">
```

2022-06-27 14:52 UTC, damiendoligez commented on doc/web/content/home.md
> +    Download/License.html).
```suggestion
    download/license.html).
```

2022-06-27 14:53 UTC, damiendoligez commented
I think you'll need to run a link checker on this thing.

2024-06-11 11:42 UTC, damiendoligez commented
I don't think we want to change our website technology at this point, and the installer program was removed some time ago.
Closing this PR without merging. Raise your hand if you disagree.

2024-06-11 11:42 UTC, closed without merging